name: bhutan_hub
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get_storage: ^2.1.1
  shared_preferences: ^2.2.3
  path_provider: ^2.1.3
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_storage: ^11.7.7
  cloud_firestore: ^4.17.5
  google_sign_in: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  connectivity_plus: ^6.0.3
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  firebase_ui_auth: ^1.14.0
  lottie: ^3.1.2
  get_it: ^7.7.0
  provider: ^6.1.2
  intl: ^0.19.0
  iconsax: ^0.0.8
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  # Image
  assets:
    - assets/images/onboarding/
    - assets/images/logo/
    - assets/images/payment/
    - assets/images/lotties/
    - assets/images/svgs/
    - assets/images/menu/
    - assets/images/social/

  # Font
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 800
