import 'dart:async';

import 'package:bhutan_hub/core/services/internet/internet_cubit.dart';
import 'package:bhutan_hub/core/store/store.dart';
import 'package:bhutan_hub/src/features/authentication/data/datasources/local.dart';
import 'package:bhutan_hub/src/features/authentication/data/datasources/remote.dart';
import 'package:bhutan_hub/src/features/authentication/data/repositories/auth.repo.implementation.dart';
import 'package:bhutan_hub/src/features/authentication/domain/repositories/authentication.dart';
import 'package:bhutan_hub/src/features/authentication/domain/usecases/cache.credentials.dart';
import 'package:bhutan_hub/src/features/authentication/domain/usecases/forgot.password.dart';
import 'package:bhutan_hub/src/features/authentication/domain/usecases/google.sso.dart';
import 'package:bhutan_hub/src/features/authentication/domain/usecases/sign.in.dart';
import 'package:bhutan_hub/src/features/authentication/domain/usecases/sign.up.dart';
import 'package:bhutan_hub/src/features/authentication/domain/usecases/update.user.dart';
import 'package:bhutan_hub/src/features/authentication/presentation/bloc/authentication_bloc.dart';
import 'package:bhutan_hub/src/features/onboarding/data/datasource/local.source.dart';
import 'package:bhutan_hub/src/features/onboarding/data/repos/onboarding.repo.impl.dart';
import 'package:bhutan_hub/src/features/onboarding/domain/repos/onboarding.repo.dart';
import 'package:bhutan_hub/src/features/onboarding/domain/usecases/cache_first_timer.dart';
import 'package:bhutan_hub/src/features/onboarding/domain/usecases/check_if_user_first_timer.dart';
import 'package:bhutan_hub/src/features/onboarding/presentations/cubit/onboarding_cubit.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:connectivity_plus/connectivity_plus.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_storage/firebase_storage.dart';
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:http/http.dart' as http;

part 'injection.main.dart';
